### ISSUE TITLE
Add `CONJUR_ACCOUNT` to the env vars list in the README file

### ISSUE THREAD

**Issue by garkler** [cyberark/summon#100] opened 2019-02-09 15:11 UTC
The README lists how to use env variables to configure the environment that the provider would use to connect to Conjur. It has all of the other variables listed, but skips `CONJUR_ACCOUNT`.

**Comment by izgeri** [comment] 2019-08-02 17:58
This is actually a duplicate of https://github.com/cyberark/summon-conjur/issues/36

**Closed by izgeri** 2019-08-02 17:58 UTC
Labels: component/summon, kind/documentation
