### ISSUE TITLE
No support for symlinking

### ISSUE THREAD

**Issue by jepperson2** [cyberark/summon#80] opened 2018-09-19 17:24 UTC
One use case I'm solving for involves fetching a secret via Summon's `!var:file` tag and then symlinking a known path to the temp file stored in that environment variable. 

Native support for this kind of symlinking would help me avoid my current undesired solution of running `summon -p ... -f ... symlinker.sh myscript.sh`

**Comment by ryanprior** [comment] 2018-09-19 17:39
One possible implementation would be to create a file instead of set an environment variable when the key is a quoted path instead of a constant.

For example:
###### secrets.yml
```
---
"~/.ssh/id_rsa": !var:file ryan/ssh/private
```

This could either create the file in `/tmp` and a symlink, or actually create the file in the target location with no symlink.

**Comment by dustinmm80** [comment] 2018-09-19 17:40
why would you symlink when you can use `/dev/shm` instead? symlinking opens you up to placing files in insecure places.

**Comment by jepperson2** [comment] 2018-09-20 18:13
In my case there are services that need secrets to be in specific file locations that I cannot change. I want to use Summon to fetch them and make them accessible from that unchangeable path. 

By using a symlink to the `/dev/shm` file that Summon populates, as soon as the Summon process terminates, that symlink points to a non-existent file (which is a good thing in my case - I don't want the secret to persist after the process terminates). 

As I understand it, this still potentially exposes that secret after the process finishes if there's an open file descriptor to that symlink, but this is still better behavior than simply writing the secret to a file, which would persist after the Summon process terminates unless I explicitly delete it.

**Comment by rpothier** [comment] 2021-02-12 21:26
Hi @jepperson2 We just added examples for adding symlinks in [201](https://github.com/cyberark/summon/pull/201). It looks to be similar to what you are doing.

**Comment by rpothier** [comment] 2021-02-17 18:38
Closing this issue as it is a duplicate of #190 .

**Closed by rpothier** 2021-02-17 18:38 UTC
